apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Release.Name }}"
data:
  PORT: "{{ .Values.port }}"
  USERS_MICROSERVICE_BASE_URL: "{{ .Values.usersMicroserviceBaseUrl }}"
