port: 3000

postgresql:
  auth:
    database: "wlosiara-pl-auth-service"
    username: "wlosiara-pl-auth-service"
  primary:
    initdb:
      scripts-configmap: "wlosiara-pl-auth-service-postgresql-initdb-scripts"

image:
  repository: null
