port: 3000

postgresql:
  auth:
    database: "wlosiara-pl-auth-service"
    username: "products-service"
  primary:
    initdb:
      scripts-configmap: "wlosiara-pl-auth-service-initdb-scripts"
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"

image:
  dockerRegistry:
    host: null # required

resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "100m"
    memory: "256Mi"
