port: 3000

postgresql:
  auth:
    database: "postgres"
    username: "auth-service"
    password: null # required
  primary:
    initdb:
      scriptsConfigMap: "wlosiara-pl-auth-service-postgresql-initdb-scripts"
      user: "wlosiara-pl-auth-service"
      password: null # required
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
    persistence:
      size: "1Gi"

usersMicroserviceBaseUrl: null # required

image:
  dockerRegistry:
    host: null # required

resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "100m"
    memory: "256Mi"
